# Generated by Django 5.2.14 on 2026-05-06 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("eid", models.IntegerField()),
                ("name", models.CharField(max_length=100)),
                ("dob", models.DateField()),
                ("email", models.EmailField(max_length=254)),
                ("city", models.CharField(max_length=100)),
                ("salary", models.FloatField()),
            ],
        ),
    ]
